apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.registry }}/{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          envFrom:
          - secretRef:
              name: cf-preproduccion
          env:
            - name: JVM_XMS
              value: {{ default "" .Values.JVM_XMS | quote }}
            - name: JVM_XMX
              value: {{ default "" .Values.JVM_XMX | quote }}
            - name: JVM_MaxMetaspaceSize
              value: {{ default "" .Values.JVM_MaxMetaspaceSize | quote }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
          failureThreshold: 3
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path:
              port: 8080
            initialDelaySeconds: 60
          volumeMounts:
          - mountPath: /tmp-jboss
            name: vol1
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
      volumes:
      - configMap:
          name: "{{ .Values.name }}-standalone-config"
        name: vol1
      
