apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JVM_XMS
              value: {{ default "" .Values.JVM_XMS | quote }}
            - name: JVM_XMX
              value: {{ default "" .Values.JVM_XMX | quote }}
            - name: JVM_MaxMetaspaceSize
              value: {{ default "" .Values.JVM_MaxMetaspaceSize | quote }}
            - name: SYS_DOMAIN
              value: {{ default "" .Values.SYS_DOMAIN | quote }}
            - name: SYS_ENVIRONMENT
              value: {{ default "" .Values.SYS_ENVIRONMENT | quote }}
            {{- $secret  := .Values.secretName -}}
            {{- range .Values.schemas }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ . }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          volumeMounts:
          - mountPath: /tmp-jboss
            name: vol1
          - mountPath: {{ .Values.persistence.path }}
            name: vol2
      volumes:
      - configMap:
          name: "{{ .Values.name }}-standalone-config"
        name: vol1
      - name: vol2
        persistentVolumeClaim:
          claimName: "{{ .Values.name }}-data-pv-claim"
      
