apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image.grafana.repository }}:{{ .Values.image.grafana.tag }}
          imagePullPolicy: {{ .Values.image.grafana.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "Password01"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: grafana.favorita.ec
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
