kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.name }}-svc"
  namespace: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
status:
  loadBalancer: {}
