kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.name }}-svc"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort
status:
  loadBalancer: {}
