apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.kafka.size }}
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka2
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kafka2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
        - name: kafka2
          image: {{ .Values.image.kafka.repository }}:{{ .Values.image.kafka.tag }}
          imagePullPolicy: {{ .Values.image.kafka.pullPolicy }}
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ default "" .Values.KAFKA2_LISTENERS | quote }}
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "earliest"
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:30093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "2000000"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_NUM_PARTITIONS
              value: "30"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper1:22181,zookeeper2:32181,zookeeper3:42181"
          ports:
            - containerPort: 9092
              name: http
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: vol1
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-kafka2
---
kind: Service
apiVersion: v1
metadata:
  name: kafka2
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka2
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30093
  type: NodePort
status:
  loadBalancer: {}