apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-zookeeper3
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.zookeeper.size }}
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs-zookeeper3
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper3
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper3
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zookeeper3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper3
    spec:
      containers:
        - name: zookeeper3
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "42181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SERVER_ID
              value: "3"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper1:22888:23888;zookeeper2:32888:33888;0.0.0.0:42888:43888"
          ports:
            - containerPort: 42181
              name: client
            - containerPort: 42888
              name: server
            - containerPort: 43888
              name: leader-election
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: vol1
          - mountPath: /var/lib/zookeeper/log
            name: vol2
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-data-zookeeper3
      - name: vol2
        persistentVolumeClaim:
          claimName: pvc-logs-zookeeper3
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: zookeeper3
  labels:
    app: zookeeper3
spec:
  ports:
  - port: 42181
    name: client
  - port: 42888
    name: server
  - port: 43888
    name: leader-election
  selector:
    app: zookeeper3
