apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-zookeeper1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.zookeeper.size }}
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs-zookeeper1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper1
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zookeeper1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      containers:
        - name: zookeeper1
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "22181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper1-hs:22888:23888;zookeeper2-hs:32888:33888;zookeeper3-hs:42888:43888"
          ports:
            - containerPort: 22181
              name: client
            - containerPort: 22888
              name: server
            - containerPort: 23888
              name: leader-election
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: vol1
          - mountPath: /var/lib/zookeeper/log
            name: vol2
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-data-zookeeper1
      - name: vol2
        persistentVolumeClaim:
          claimName: pvc-logs-zookeeper1
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zookeeper1
  ports:
  - protocol: TCP
    port: 22181
    targetPort: 22181
  type: ClusterIP
status:
  loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper1-hs
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zookeeper1
  ports:
  - port: 22888
    name: server
  - port: 23888
    name: leader-election
  type: ClusterIP
status:
  loadBalancer: {}
