replicas: 1

namespace: cf-kafka

image:
  zookeeper:
    repository: confluentinc/cp-zookeeper
    tag: latest
    pullPolicy: Always
  kafka:
    repository: confluentinc/cp-kafka
    tag: latest
    pullPolicy: Always
