apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: 2181
            - name: ZOOKEEPER_INIT_LIMIT
              value: 5
            - name: ZOOKEEPER_SERVER_ID
              value: 2
            - name: ZOOKEEPER_SYNC_LIMIT
              value: 2
            - name: ZOOKEEPER_TICK_TIME
              value: 2000
            - name: ZOO_SERVERS
              value: server.1=0.0.0.0:2888:3888;2181
          ports:
            - containerPort: 2181
              name: http
              protocol: TCP      
