apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kafka1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
        - name: kafka1
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://queue-kafka:30092,EXTERNAL://kafka1:9092"
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "earliest"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENERS
              value: "INTERNAL"
            - name: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:30092
              value: "INTERNAL"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "2000000"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_NUM_PARTITIONS
              value: "30"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper1:2181"
          ports:
            - containerPort: 9092
              name: http
              protocol: TCP

kind: Service
apiVersion: v1
metadata:
  name: kafka1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka1
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
status:
  loadBalancer: {}
 
