kind: Service
apiVersion: v1
metadata:
  name: kafka1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka1
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
  type: NodePort
status:
  loadBalancer: {}
 
