apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-zookeeper3
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.zookeeper.size }}
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs-zookeeper3
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper3
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper3
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zookeeper3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper3
    spec:
      containers:
        - name: zookeeper3
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SERVER_ID
              value: "3"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOO_SERVERS
              value: "server.1=zookeeper1:2888:3888;2181 server.2=zookeeper3:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"
          ports:
            - containerPort: 2181
              name: http
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: vol1
          - mountPath: /var/lib/zookeeper/log
            name: vol2
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-data-zookeeper3
      - name: vol2
        persistentVolumeClaim:
          claimName: pvc-logs-zookeeper3
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper3
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zookeeper3
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
  type: ClusterIP
status:
  loadBalancer: {}