apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-zookeeper4
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.zookeeper.size }}
  storageClassName: {{ .Values.storage.class }}
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper4
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper4
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zookeeper4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper4
    spec:
      containers:
        - name: zookeeper4
          image: {{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}
          imagePullPolicy: {{ .Values.image.zookeeper.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "42181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SERVER_ID
              value: "4"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888;0.0.0.0:52888:53888;zookeeper5:62888:63888"
          ports:
            - containerPort: 52181
              name: client
            - containerPort: 52888
              name: server
            - containerPort: 53888
              name: leader-election
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: vol1
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-data-zookeeper4
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: zookeeper4
  labels:
    app: zookeeper4
spec:
  ports:
  - port: 52181
    name: client
  - port: 52888
    name: server
  - port: 53888
    name: leader-election
  selector:
    app: zookeeper4
